# syntax=docker.io/docker/dockerfile:1

FROM node:22 AS base

# basic setup
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y \
  vim \
  curl \
  git \
  openssh-server

# Configure SSH (Change your password to something strong)
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
RUN mkdir -p /var/run/sshd && ssh-keygen -A
RUN echo 'root:123456' | chpasswd

# run sshd
WORKDIR /
CMD ["/usr/sbin/sshd", "-D"]