import './globals.css';
import '@chinese-fonts/lxgwwenkai/dist/LXGWWenKai-Regular/result.css';
// import 'animate.css'; // has conflict with tailwind animate-pulse
import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import { enableMapSet } from 'immer';
import dayjs from 'dayjs';
import isLeapYear from 'dayjs/plugin/isLeapYear';
import relativeTime from 'dayjs/plugin/relativeTime';
import duration from 'dayjs/plugin/duration';
import { RootLayerRenderer } from '@/components/ui/rootLayer';
import { ThemeProvider } from '@/components/ui/theme-provider';
import { TooltipProvider } from '@/components/ui/tooltip';
import { NuqsAdapter } from 'nuqs/adapters/next';
import EasyScroller from '@/components/advanced/EasyScroller';
import React from 'react';

enableMapSet();
dayjs.extend(relativeTime);
dayjs.extend(duration);
dayjs.extend(isLeapYear);
// dayjs.locale('zh-cn');

export const metadata: Metadata = {
  title: 'next-template',
  icons: {
    icon: '/images/logo.png',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased dark:bg-gray-900`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <TooltipProvider>
            <Toaster position="top-center" />
            <RootLayerRenderer />
            <NuqsAdapter>{children}</NuqsAdapter>
            <EasyScroller />
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
